version: '3'

services:

    reverse-proxy:
        image: jwilder/nginx-proxy
        container_name: "reverse-proxy"
        networks:
            - local
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - "${PWD}/default_location:/etc/nginx/vhost.d/default_location"
        ports:
            - "80:80"
        environment:
            - DEFAULT_HOST=portainer.${MOODLE_SITE_NAME}
            - NETWORK_ACCESS=internal
            - CONFIG=[{"Path":"/","Access":"allow","Addresses":["10.0.0.0/8","192.168.0.0/16","172.0.0.0/8","127.0.0.1"]}]

    templates:
        image: portainer/templates
        container_name: "portainer-templates"
        networks:
            - local
        volumes:
            - "${PWD}/templates.json:/usr/share/nginx/html/templates.json"

    portainer:
        image: portainer/portainer
        container_name: "portainer-app"
        #command: --templates http://templates/templates.json -H unix:///var/run/docker.sock --no-auth
        command: -H unix:///var/run/docker.sock --no-auth
        networks:
            - local
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        expose:
            - "9000"
        environment:
            - VIRTUAL_HOST=portainer.${MOODLE_SITE_NAME}

    sherpa:
        image: djenriquez/sherpa
        container_name: "sherpa"
        command: --allow
        networks:
            - local
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        expose:
            - "4550"
        environment:
            - VIRTUAL_HOST=dockerapi.${MOODLE_SITE_NAME}

    selenium:
        image: "selenium/standalone-chrome-debug:3.5.2"
        container_name: "selenium"
        networks:
            - local
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "5900:5900"
        environment:
            - VNC_NO_PASSWORD=1

    forge:
        image: ryanwyllie/moodle-forge
        container_name: "forge"
        networks:
            - local
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        environment:
            - VIRTUAL_HOST=forge.${MOODLE_SITE_NAME}

networks:
    local:
        driver: bridge

volumes:
    portainer_data:
