version: '2'

services:

    reverse-proxy:
        image: jwilder/nginx-proxy
        container_name: "reverse-proxy"
        networks:
            - local
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - "80:80"
        environment:
            - DEFAULT_HOST=admin.${MOODLE_SITE_NAME}

    templates:
        image: portainer/templates
        container_name: "portainer-templates"
        networks:
            - local
        volumes:
            - "${PWD}/templates.json:/usr/share/nginx/html/templates.json"

    portainer:
        image: portainer/portainer
        container_name: "portainer-app"
        command: --templates http://templates/templates.json -H unix:///var/run/docker.sock --no-auth
        networks:
            - local
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        expose:
            - "9000"
        environment:
            - VIRTUAL_HOST=admin.${MOODLE_SITE_NAME}

    stable-master:
        image: moodlehq/moodle-php-apache:7.1
        container_name: "stable-master"
        networks:
            - local
            - stablemaster
        volumes:
            - "${MOODLE_CODE_DIRECTORY}/stable_master/moodle:/var/www/html"
        expose:
            - "80"
            - "443"
        environment:
            - VIRTUAL_HOST=stablemaster.${MOODLE_SITE_NAME}
            - MOODLE_DOCKER_DBTYPE=pgsql
            - MOODLE_DOCKER_DBHOST=pgsql-master
            - MOODLE_DOCKER_DBNAME=moodle
            - MOODLE_DOCKER_DBUSER=moodle
            - MOODLE_DOCKER_DBPASS=m@0dl3ing
            - MOODLE_DOCKER_DBPREFIX=stbm
            - MOODLE_DOCKER_BROWSER=chrome

    pgsql-master:
        image: postgres:9.6.7
        container_name: "pgsql-master"
        networks:
            - stablemaster
        environment:
            - POSTGRES_USER=moodle
            - POSTGRES_PASSWORD=m@0dl3ing
            - POSTGRES_DB=moodle

    stable-34:
        image: moodlehq/moodle-php-apache:7.1
        container_name: "stable-34"
        networks:
            - local
            - stable34
        volumes:
            - "${MOODLE_CODE_DIRECTORY}/stable_34/moodle:/var/www/html"
        expose:
            - "80"
            - "443"
        environment:
            - VIRTUAL_HOST=stable34.${MOODLE_SITE_NAME}
            - MOODLE_DOCKER_DBTYPE=pgsql
            - MOODLE_DOCKER_DBHOST=pgsql-34
            - MOODLE_DOCKER_DBNAME=moodle
            - MOODLE_DOCKER_DBUSER=moodle
            - MOODLE_DOCKER_DBPASS=m@0dl3ing
            - MOODLE_DOCKER_DBPREFIX=stb34
            - MOODLE_DOCKER_BROWSER=chrome

    pgsql-34:
        image: postgres:9.6.7
        container_name: "pgsql-34"
        networks:
            - stable34
        environment:
            - POSTGRES_USER=moodle
            - POSTGRES_PASSWORD=m@0dl3ing
            - POSTGRES_DB=moodle

    stable-33:
        image: moodlehq/moodle-php-apache:7.1
        container_name: "stable-33"
        networks:
            - local
            - stable33
        volumes:
            - "${MOODLE_CODE_DIRECTORY}/stable_33/moodle:/var/www/html"
        expose:
            - "80"
            - "443"
        environment:
            - VIRTUAL_HOST=stable33.${MOODLE_SITE_NAME}
            - MOODLE_DOCKER_DBTYPE=pgsql
            - MOODLE_DOCKER_DBHOST=pgsql-33
            - MOODLE_DOCKER_DBNAME=moodle
            - MOODLE_DOCKER_DBUSER=moodle
            - MOODLE_DOCKER_DBPASS=m@0dl3ing
            - MOODLE_DOCKER_DBPREFIX=stb33
            - MOODLE_DOCKER_BROWSER=chrome

    pgsql-33:
        image: postgres:9.6.7
        container_name: "pgsql-33"
        networks:
            - stable33
        environment:
            - POSTGRES_USER=moodle
            - POSTGRES_PASSWORD=m@0dl3ing
            - POSTGRES_DB=moodle

    integration-master:
        image: moodlehq/moodle-php-apache:7.1
        container_name: "integration-master"
        networks:
            - local
            - integrationmaster
        volumes:
            - "${MOODLE_CODE_DIRECTORY}/integration_master/moodle:/var/www/html"
        expose:
            - "80"
            - "443"
        environment:
            - VIRTUAL_HOST=integrationmaster.${MOODLE_SITE_NAME}
            - MOODLE_DOCKER_DBTYPE=pgsql
            - MOODLE_DOCKER_DBHOST=pgsql-int-master
            - MOODLE_DOCKER_DBNAME=moodle
            - MOODLE_DOCKER_DBUSER=moodle
            - MOODLE_DOCKER_DBPASS=m@0dl3ing
            - MOODLE_DOCKER_DBPREFIX=intm
            - MOODLE_DOCKER_BROWSER=chrome

    pgsql-int-master:
        image: postgres:9.6.7
        container_name: "pgsql-int-master"
        networks:
            - integrationmaster
        environment:
            - POSTGRES_USER=moodle
            - POSTGRES_PASSWORD=m@0dl3ing
            - POSTGRES_DB=moodle

    integration-34:
        image: moodlehq/moodle-php-apache:7.1
        container_name: "integration-34"
        networks:
            - local
            - integration34
        volumes:
            - "${MOODLE_CODE_DIRECTORY}/integration_34/moodle:/var/www/html"
        expose:
            - "80"
            - "443"
        environment:
            - VIRTUAL_HOST=integration34.${MOODLE_SITE_NAME}
            - MOODLE_DOCKER_DBTYPE=pgsql
            - MOODLE_DOCKER_DBHOST=pgsql-int-34
            - MOODLE_DOCKER_DBNAME=moodle
            - MOODLE_DOCKER_DBUSER=moodle
            - MOODLE_DOCKER_DBPASS=m@0dl3ing
            - MOODLE_DOCKER_DBPREFIX=int34
            - MOODLE_DOCKER_BROWSER=chrome

    pgsql-int-34:
        image: postgres:9.6.7
        container_name: "pgsql-int-34"
        networks:
            - integration34
        environment:
            - POSTGRES_USER=moodle
            - POSTGRES_PASSWORD=m@0dl3ing
            - POSTGRES_DB=moodle

    integration-33:
        image: moodlehq/moodle-php-apache:7.1
        container_name: "integration-33"
        networks:
            - local
            - integration33
        volumes:
            - "${MOODLE_CODE_DIRECTORY}/integration_33/moodle:/var/www/html"
        expose:
            - "80"
            - "443"
        environment:
            - VIRTUAL_HOST=integration33.${MOODLE_SITE_NAME}
            - MOODLE_DOCKER_DBTYPE=pgsql
            - MOODLE_DOCKER_DBHOST=pgsql-int-33
            - MOODLE_DOCKER_DBNAME=moodle
            - MOODLE_DOCKER_DBUSER=moodle
            - MOODLE_DOCKER_DBPASS=m@0dl3ing
            - MOODLE_DOCKER_DBPREFIX=int33
            - MOODLE_DOCKER_BROWSER=chrome

    pgsql-int-33:
        image: postgres:9.6.7
        container_name: "pgsql-int-33"
        networks:
            - integration33
        environment:
            - POSTGRES_USER=moodle
            - POSTGRES_PASSWORD=m@0dl3ing
            - POSTGRES_DB=moodle

networks:
    local:
        driver: bridge
    stablemaster:
        driver: bridge
    stable34:
        driver: bridge
    stable33:
        driver: bridge
    integrationmaster:
        driver: bridge
    integration34:
        driver: bridge
    integration33:
        driver: bridge

volumes:
    portainer_data:
